[project]
name = "telegram-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flask>=3.1.2",
    "piexif>=1.1.3",
    "pillow>=11.3.0",
    "pycryptodome>=3.23.0",
    "python-telegram-bot>=22.3",
]
